# Generated by Django 4.1.3 on 2023-04-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_name',
        ),
    ]
